---

name: Hugo Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Hugo
        env:
          HUGO_VERSION: 0.80.0
        run: |
          echo "installing hugo $HUGO_VERSION"
          curl -sL -o /tmp/hugo.deb \
          https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb && \
          sudo dpkg -i /tmp/hugo.deb && \
          rm /tmp/hugo.deb

      - name: Test Build
        run: hugo
